# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Wake Commerce Test Workflow

on:
  push:
    branches: [ "dev", "master" ]
  pull_request:
    branches: [ "dev", "master" ]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/WakeCommerce/WakeCommerce.sln
    - name: Build
      run: dotnet build ./src/WakeCommerce/WakeCommerce.sln --no-restore
    - name: Integration Tests
      run: dotnet test ./src/WakeCommerce/Integration.Tests/Integration.Tests.csproj --no-build --verbosity normal --logger "trx;LogFileName=IntegrationTests.trx"
    - name: Unit Tests
      run: dotnet test ./src/WakeCommerce/Unit.Tests/Unit.Tests.csproj --no-build --verbosity normal --logger "trx;LogFileName=UnitTests.trx"
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: (!cancelled())
      with:
        files: |
            ./src/WakeCommerce/Integration.Tests/TestResults/IntegrationTests.trx
            ./src/WakeCommerce/Unit.Tests/TestResults/UnitTests.trx
